"""
runner.py  —  Trace Flask API entry point
Start with:  python runner.py

Policy
------
* ONLY syntax errors block the pipeline and return an error response.
* Runtime / logical errors still produce a full interactive response showing
  all traced steps.  has_runtime_error=True lets the frontend show a banner.
* Each step now includes an 'explanation' field generated by explainer.py.
* Custom stdin can be passed in the POST body as 'stdin'.
* 'code_type' can be 'complete' (default) or 'leetcode'.
"""
import os
import uuid
import sys

from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)

from tracer.syntax_checker  import SyntaxChecker
from tracer.python_tracer   import PythonTracer
from tracer.js_tracer       import JSTracer
from tracer.c_tracer        import CTracer
from tracer.cpp_tracer      import CppTracer
from tracer.explainer       import generate as explain_step
from video.frame_builder    import FrameBuilder
from video.video_exporter   import VideoExporter

app = Flask(__name__)
CORS(app)

VIDEOS_DIR   = os.path.join(BASE_DIR, "static", "videos")
FRONTEND_DIR = os.path.join(BASE_DIR, "..", "frontend")
os.makedirs(VIDEOS_DIR, exist_ok=True)

SUPPORTED_LANGUAGES = {
    "python":     "Python 3",
    "javascript": "JavaScript (Node.js)",
    "c":          "C (GCC/GDB)",
    "cpp":        "C++ (G++/GDB)",
}

SAMPLE_CODE = {
    "python": """\
# Find the largest number in an array
arr = [64, 34, 25, 12, 22, 11, 90]
max_val = arr[0]
for i in range(1, len(arr)):
    if arr[i] > max_val:
        max_val = arr[i]
print("Largest:", max_val)
""",
    "javascript": """\
// Bubble Sort
let arr = [64, 34, 25, 12, 22, 11, 90];
let n = arr.length;
for (let i = 0; i < n - 1; i++) {
  for (let j = 0; j < n - i - 1; j++) {
    if (arr[j] > arr[j + 1]) {
      let temp = arr[j];
      arr[j] = arr[j + 1];
      arr[j + 1] = temp;
    }
  }
}
console.log(arr);
""",
    "c": """\
#include <stdio.h>
int main() {
    int arr[] = {64, 34, 25, 12, 22, 11, 90};
    int n = 7, max_val = arr[0];
    for (int i = 1; i < n; i++) {
        if (arr[i] > max_val)
            max_val = arr[i];
    }
    printf("Largest: %d\\n", max_val);
    return 0;
}
""",
    "cpp": """\
#include <iostream>
#include <vector>
using namespace std;
int main() {
    vector<int> arr = {64, 34, 25, 12, 22, 11, 90};
    int n = arr.size(), max_val = arr[0];
    for (int i = 1; i < n; i++) {
        if (arr[i] > max_val)
            max_val = arr[i];
    }
    cout << "Largest: " << max_val << endl;
    return 0;
}
""",
}


# ── API: language list ────────────────────────────────────────────────────────
@app.route("/api/languages", methods=["GET"])
def get_languages():
    return jsonify({"languages": SUPPORTED_LANGUAGES})


# ── API: sample code ──────────────────────────────────────────────────────────
@app.route("/api/sample", methods=["GET"])
def get_sample():
    lang = request.args.get("language", "python").lower()
    return jsonify({"code": SAMPLE_CODE.get(lang, SAMPLE_CODE["python"])})


# ── API: main trace endpoint ──────────────────────────────────────────────────
@app.route("/api/trace", methods=["POST"])
def trace():
    data      = request.get_json(silent=True) or {}
    code      = (data.get("code") or "").strip()
    language  = (data.get("language") or "python").lower()
    stdin_in  = (data.get("stdin") or "").strip()      # custom input
    code_type = (data.get("code_type") or "complete")  # 'complete' | 'leetcode'
    make_video= bool(data.get("make_video", False))    # video is optional now

    if not code:
        return jsonify({"error": "No code provided."}), 400

    if language not in SUPPORTED_LANGUAGES:
        return jsonify({"error": f"Unsupported language: '{language}'."}), 400

    # ── 1. Syntax check ───────────────────────────────────────────────────────
    checker       = SyntaxChecker()
    syntax_result = checker.check(code, language)
    if not syntax_result["valid"]:
        return jsonify({
            "syntax_error": True,
            "error":        syntax_result["error"],
            "error_line":   syntax_result.get("line"),
        }), 200

    # ── 2. Run tracer ─────────────────────────────────────────────────────────
    try:
        if language == "python":
            steps = PythonTracer().trace(code, stdin=stdin_in)
        elif language == "javascript":
            steps = JSTracer().trace(code)
        elif language == "cpp":
            steps = CppTracer().trace(code)
        else:  # c
            steps = CTracer().trace(code)
    except Exception as exc:
        return jsonify({"error": f"Tracer internal error: {exc}"}), 500

    if not steps:
        return jsonify({"error": "No execution steps captured."}), 500

    # ── 3. Attach explanations ────────────────────────────────────────────────
    code_lines = code.split("\n")
    for i, step in enumerate(steps):
        prev = steps[i - 1] if i > 0 else None
        try:
            step["explanation"] = explain_step(step, prev, code_lines)
        except Exception:
            step["explanation"] = f"Executing line {step.get('line', '?')}."

    # ── 4. Detect runtime error ───────────────────────────────────────────────
    has_runtime_error = False
    runtime_error_msg = None
    for s in steps:
        if s.get("event") in ("error", "exception") and s.get("error"):
            has_runtime_error = True
            if runtime_error_msg is None:
                runtime_error_msg = s["error"]

    # ── 5. Build response ─────────────────────────────────────────────────────
    response = {
        "steps":             steps,
        "total_steps":       len(steps),
        "has_runtime_error": has_runtime_error,
        "runtime_error_msg": runtime_error_msg,
        "language":          language,
        "code_lines":        code_lines,
    }

    # ── 6. (Optional) Generate video ─────────────────────────────────────────
    if make_video:
        try:
            builder     = FrameBuilder(code_lines, language)
            frame_paths = builder.build_frames(
                steps,
                has_runtime_error=has_runtime_error,
                runtime_error_msg=runtime_error_msg,
            )
            video_id       = str(uuid.uuid4())[:8]
            video_filename = f"trace_{video_id}.mp4"
            video_path     = os.path.join(VIDEOS_DIR, video_filename)
            VideoExporter().export(frame_paths, video_path)
            response["video_url"] = f"/static/videos/{video_filename}"
        except Exception as exc:
            response["video_error"] = str(exc)
        finally:
            for fp in frame_paths if "frame_paths" in dir() else []:
                try: os.remove(fp)
                except OSError: pass

    return jsonify(response)


# ── Static / frontend routes ──────────────────────────────────────────────────
@app.route("/static/videos/<path:filename>")
def serve_video(filename):
    return send_from_directory(VIDEOS_DIR, filename)

@app.route("/")
def index():
    return send_from_directory(FRONTEND_DIR, "index.html")

@app.route("/css/<path:filename>")
def serve_css(filename):
    return send_from_directory(os.path.join(FRONTEND_DIR, "css"), filename)

@app.route("/js/<path:filename>")
def serve_js(filename):
    return send_from_directory(os.path.join(FRONTEND_DIR, "js"), filename)

@app.route("/favicon.ico")
def favicon():
    return "", 204


# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\n  [trace]  Code Execution Visualizer")
    print("  Running at  ->  http://localhost:5000\n")
    app.run(debug=True, port=5000, use_reloader=False)
